reciever/config/routes.rb
Playmobil::Application.routes.draw do

  resources :ingests

  resources :video_signals
  mount Resque::Server.new, at: "/resque"

  mount RailsAdmin::Engine => '/receiver', as: 'rails_admin'

end

reciever/app/models/ingest.rb
class Ingest
  include Mongoid::Document

  field :url, type: String

  validates_presence_of :url

end

reciever/app/models/video_signal.rb
class VideoSignal
  include Mongoid::Document

  field :name, type: String
  field :source, type: String
  field :bitrate, type: Array

end

reciever/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

reciever/app/controllers/ingests_controller.rb
class IngestsController < ApplicationController
  before_action :set_ingest, only: [:show, :edit, :update, :destroy]

  # GET /ingests
  # GET /ingests.json
  def index
    @ingests = Ingest.all
  end

  # GET /ingests/1
  # GET /ingests/1.json
  def show
  end

  # GET /ingests/new
  def new
    @ingest = Ingest.new
  end

  # GET /ingests/1/edit
  def edit
  end

  # POST /ingests
  # POST /ingests.json
  def create
    @ingest = Ingest.new(ingest_params)

    respond_to do |format|
      if @ingest.save
        format.html { redirect_to @ingest, notice: 'Ingest was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ingest }
      else
        format.html { render action: 'new' }
        format.json { render json: @ingest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingests/1
  # PATCH/PUT /ingests/1.json
  def update
    respond_to do |format|
      if @ingest.update(ingest_params)
        format.html { redirect_to @ingest, notice: 'Ingest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ingest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingests/1
  # DELETE /ingests/1.json
  def destroy
    @ingest.destroy
    respond_to do |format|
      format.html { redirect_to ingests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingest
      @ingest = Ingest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingest_params
      params.require(:ingest).permit(:host)
    end
end

reciever/app/controllers/video_signals_controller.rb
class VideoSignalsController < ApplicationController
  before_action :set_video_signal, only: [:show, :edit, :update, :destroy]

  # GET /video_signals
  # GET /video_signals.json
  def index
    @video_signals = VideoSignal.all
  end

  # GET /video_signals/1
  # GET /video_signals/1.json
  def show
  end

  # GET /video_signals/new
  def new
    @video_signal = VideoSignal.new
  end

  # GET /video_signals/1/edit
  def edit
  end

  # POST /video_signals
  # POST /video_signals.json
  def create
    @video_signal = VideoSignal.new(video_signal_params)
    @ingest = Ingest.last.url
    @video_signal.source = @ingest
    respond_to do |format|
      if @video_signal.save
        format.html { redirect_to @video_signal, notice: 'Video signal was successfully created.' }
        format.json { render action: 'show', status: :created, location: @video_signal }
      else
        format.html { render action: 'new' }
        format.json { render json: @video_signal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /video_signals/1
  # PATCH/PUT /video_signals/1.json
  def update
    respond_to do |format|
      if @video_signal.update(video_signal_params)
        format.html { redirect_to @video_signal, notice: 'Video signal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @video_signal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /video_signals/1
  # DELETE /video_signals/1.json
  def destroy
    @video_signal.destroy
    respond_to do |format|
      format.html { redirect_to video_signals_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video_signal
      @video_signal = VideoSignal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_signal_params
      params.require(:video_signal).permit(:name)
    end
end

reciever/app/helpers/application_helper.rb
module ApplicationHelper
end

reciever/app/helpers/ingests_helper.rb
module IngestsHelper
end

reciever/app/helpers/video_signals_helper.rb
module VideoSignalsHelper
end

reciever/app/views/ingests/_form.html.erb
<%= form_for(@ingest) do |f| %>
  <% if @ingest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingest.errors.count, "error") %> prohibited this ingest from being saved:</h2>

      <ul>
      <% @ingest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :host %><br>
    <%= f.text_field :host %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

reciever/app/views/ingests/edit.html.erb
<h1>Editing ingest</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingest %> |
<%= link_to 'Back', ingests_path %>

reciever/app/views/ingests/index.html.erb
<h1>Listing ingests</h1>

<table>
  <thead>
    <tr>
      <th>Host</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ingests.each do |ingest| %>
      <tr>
        <td><%= ingest.host %></td>
        <td><%= link_to 'Show', ingest %></td>
        <td><%= link_to 'Edit', edit_ingest_path(ingest) %></td>
        <td><%= link_to 'Destroy', ingest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingest', new_ingest_path %>

reciever/app/views/ingests/new.html.erb
<h1>New ingest</h1>

<%= render 'form' %>

<%= link_to 'Back', ingests_path %>

reciever/app/views/ingests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Host:</strong>
  <%= @ingest.host %>
</p>

<%= link_to 'Edit', edit_ingest_path(@ingest) %> |
<%= link_to 'Back', ingests_path %>

reciever/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Playmobil Receiver</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>

<nav class="navbar navbar-playmobil navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-9">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%=video_signals_path%>"><img alt="Brand" src="/assets/playmobil.png"></a>
      <p class="navbar-text navbar">Playmobil</p>
    </div>

  </div>
</nav>


<div class="container">
  <div class="row">
    <% if flash[:notice] %>
      <div class="alert alert-warning" role="alert"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:success] %>
      <div class="alert alert-success message" role="alert"><%= flash[:success] %></div>
    <% end %>
    <% if flash[:error] %>
      <div class="alert alert-danger message" role="alert"><%= flash[:error] %></div>
    <% end %>



    <div class="span9"><%= yield %></div>
  </div>
</div>


</body>
</html>

reciever/app/views/video_signals/_form.html.erb
<%= form_for @video_signal, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                video_signals_path, :class => 'btn' %>
  </div>
<% end %>

reciever/app/views/video_signals/edit.html.erb
<%- model_class = VideoSignal -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

reciever/app/views/video_signals/index.html.erb
<%- model_class = VideoSignal -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:source) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @video_signals.each do |video_signal| %>
      <tr>
        <td><%= link_to video_signal.id, video_signal_path(video_signal) %></td>
        <td><%= video_signal.name %></td>
        <td><%= video_signal.source %></td>
        <td><%=l video_signal.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_video_signal_path(video_signal), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      video_signal_path(video_signal),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_video_signal_path,
            :class => 'btn btn-primary' %>

reciever/app/views/video_signals/new.html.erb
<%- model_class = VideoSignal -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

reciever/app/views/video_signals/show.html.erb
<%- model_class = VideoSignal -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @video_signal.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:source) %>:</strong></dt>
  <dd><%= @video_signal.source %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              video_signals_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_video_signal_path(@video_signal), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              video_signal_path(@video_signal),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>